id = "react-snippets"
name = "React Snippets"
version = "1.0.6"
schema_version = 1
authors = ["Tamim Hasan <me@tamimhasan.com>"]
description = "React snippets for zed code editor"
repository = "https://github.com/tamimhasandev/react-snippets"
snippets = "./snippets/javascript.json"